### ISSUE TITLE
build Angular project fails

### ISSUE THREAD

**Issue by jafio** [teambit/envs#99]
## Expected Behavior
running `bit build` in an Angular project with bit should works

## Actual Behavior
The command show an error

## Steps to Reproduce the Problem

  1. Follow the official Angular tutorial (https://docs.bit.dev/docs/tutorials/bit-angular-tutorial) with the tutorial project
  2. At the step to build the project, The following error is shown:
```
error: bit failed to load bit.envs/compilers/angular@0.2.1 with the following exception:
Cannot find module '/home/jaf/Téléchargements/bit-angular-tutorial-master/.bit/components/compilers/angular/bit.envs/0.2.1/dist/angular/tsconfig.json'.
Error: Cannot find module '/home/jaf/Téléchargements/bit-angular-tutorial-master/.bit/components/compilers/angular/bit.envs/0.2.1/dist/angular/tsconfig.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/jaf/Téléchargements/bit-angular-tutorial-master/.bit/components/compilers/angular/bit.envs/0.2.1/dist/angular/angular.js:55:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at /usr/lib/node_modules/bit-bin/dist/extensions/base-extension.js:569:24
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/lib/node_modules/bit-bin/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/lib/node_modules/bit-bin/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/usr/lib/node_modules/bit-bin/node_modules/bluebird/js/release/promise.js:609:26)
```

## Specifications

  - Bit version: 14.7.6
  - Node version: 11.15.0
  - npm / yarn version: npm v6.14.1
  - Platform: Linux Debian Buster
  - Compiler / Tester (include version): compiler: bit.envs/compilers/angular@0.2.1

**Comment by jafio** [comment]
If I downgrade the compiler to version 0.2.0, it works. The problem is really with the version 0.2.1

**Comment by nivensookharan** [comment]
@jafio how did you downgrade the compiler? mine still seems to be importing 0.2.1

**Comment by nivensookharan** [comment]
ok i got it to work if anyone else is looking for this

`bit import bit.envs/compilers/angular@0.2.0 --compiler -c`

**Comment by Tallyb** [comment]
@nivensookharan  - there's a new version of angular compiler - 9.0.0. can you try with it?

**Comment by jafio** [comment]
@Tallyb I tried angular compiler 9.0.0 and it works.
